P8105 Homework 3 \[td2704\]
================

## Problem 1

``` r
data("instacart")
```

``` r
instacart
```

    ## # A tibble: 1,384,617 × 15
    ##    order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##       <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ##  1        1      49302                 1         1  112108 train               4
    ##  2        1      11109                 2         1  112108 train               4
    ##  3        1      10246                 3         0  112108 train               4
    ##  4        1      49683                 4         0  112108 train               4
    ##  5        1      43633                 5         1  112108 train               4
    ##  6        1      13176                 6         0  112108 train               4
    ##  7        1      47209                 7         0  112108 train               4
    ##  8        1      22035                 8         1  112108 train               4
    ##  9       36      39612                 1         0   79431 train              23
    ## 10       36      19660                 2         1   79431 train              23
    ## # … with 1,384,607 more rows, and 8 more variables: order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>, product_name <chr>,
    ## #   aisle_id <int>, department_id <int>, aisle <chr>, department <chr>

### Describing the instacart dataset.

The instacart dataset has 1384617 rows of 15 variables: order\_id,
product\_id, add\_to\_cart\_order, reordered, user\_id, eval\_set,
order\_number, order\_dow, order\_hour\_of\_day,
days\_since\_prior\_order, product\_name, aisle\_id, department\_id,
aisle, department. It is a tibble that lists products in each order with
an associated order\_number and user\_id, along with other order info
such as when they last ordered and what time this order was placed. It
covers a range of 39123 products in 21 departments from 131209 orders by
131209 users. For example, the first row of the dataset describes
Bulgarian Yogurt from order 1 by user 112108; it is described to be in
the yogurt aisle in the dairy eggs department. It was added to cart by
user 112108 1 time(s); and it had been 9 days since this user last
ordered. As another example of a row of data in this dataset, the 10th
row of the dataset describes Spring Water from order 36 by user 79431;
it is described to be in the water seltzer sparkling water aisle in the
beverages department. It was added to cart by user 79431 2 time(s); and
it had been 30 days since this user last ordered.

### How many aisles are there, and which aisles are the most items ordered from?

There are 134 aisles in this dataset.

``` r
aisle_info = 
  instacart %>%
  group_by(aisle, aisle_id) %>%
  count(aisle) %>%
  arrange(desc(n)) %>%
  rename(num_items_ordered = n)
  
sum(pull(aisle_info,num_items_ordered)) # to make sure we total the number of rows in dataset
```

    ## [1] 1384617

``` r
aisle_info
```

    ## # A tibble: 134 × 3
    ## # Groups:   aisle, aisle_id [134]
    ##    aisle                         aisle_id num_items_ordered
    ##    <chr>                            <int>             <int>
    ##  1 fresh vegetables                    83            150609
    ##  2 fresh fruits                        24            150473
    ##  3 packaged vegetables fruits         123             78493
    ##  4 yogurt                             120             55240
    ##  5 packaged cheese                     21             41699
    ##  6 water seltzer sparkling water      115             36617
    ##  7 milk                                84             32644
    ##  8 chips pretzels                     107             31269
    ##  9 soy lactosefree                     91             26240
    ## 10 bread                              112             23635
    ## # … with 124 more rows

It seems to be that the top 5 aisles most ordered from are fresh
vegetables, fresh fruits, packaged vegetables fruits, yogurt, packaged
cheese.

### Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it.

We can use our aisle\_info dataframe from above for this.

``` r
aisle_info %>%
  filter(num_items_ordered > 10000) %>%
  ggplot(aes(x=num_items_ordered, y=reorder(aisle, num_items_ordered))) +
  geom_bar(stat='identity') + 
  ggtitle("Number of items ordered in each aisle (more than 10000)") +
  xlab("Number items ordered") + ylab("Aisle name")
```

![](p8105_hw3_td2704_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

### Make a table showing the three most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”. Include the number of times each item is ordered in your table.

``` r
instacart %>%
  filter(aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>%
  group_by(aisle, aisle_id,product_name, product_id) %>%
  count(product_name) %>%
  rename(num_items_ordered=n) %>%
  arrange(desc(num_items_ordered)) %>%
  group_by(aisle) %>%
  slice_max(num_items_ordered,n=3) %>%
  arrange(desc(num_items_ordered)) %>%
  knitr::kable()
```

| aisle                      | aisle\_id | product\_name                                 | product\_id | num\_items\_ordered |
|:---------------------------|----------:|:----------------------------------------------|------------:|--------------------:|
| packaged vegetables fruits |       123 | Organic Baby Spinach                          |       21903 |                9784 |
| packaged vegetables fruits |       123 | Organic Raspberries                           |       27966 |                5546 |
| packaged vegetables fruits |       123 | Organic Blueberries                           |       39275 |                4966 |
| baking ingredients         |        17 | Light Brown Sugar                             |       23537 |                 499 |
| baking ingredients         |        17 | Pure Baking Soda                              |       23405 |                 387 |
| baking ingredients         |        17 | Cane Sugar                                    |       49533 |                 336 |
| dog food care              |        40 | Snack Sticks Chicken & Rice Recipe Dog Treats |         722 |                  30 |
| dog food care              |        40 | Organix Chicken & Brown Rice Recipe           |       23329 |                  28 |
| dog food care              |        40 | Small Dog Biscuits                            |       17471 |                  26 |

### Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

``` r
instacart %>%
  filter(product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>%
  select(product_name,product_id,order_dow,order_hour_of_day) %>%
  group_by(product_name, product_id, order_dow) %>%
  summarize(mean_hour_of_day = mean(order_hour_of_day,
                                    .groups=c(product_name, product_id, order_dow))) %>%
  pivot_wider(
    names_from=order_dow,
    values_from=mean_hour_of_day) %>%
  knitr::kable(digits=2)
```

    ## `summarise()` has grouped output by 'product_name', 'product_id'. You can override using the `.groups` argument.

| product\_name    | product\_id |     0 |     1 |     2 |     3 |     4 |     5 |     6 |
|:-----------------|------------:|------:|------:|------:|------:|------:|------:|------:|
| Coffee Ice Cream |       17334 | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples |        3798 | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |
